/**
 * Reads the local Minecraft jar and writes src/data/blocks.catalog.data.ts and
 * src/data/blocks.catalog.ids.json. Run by hand: `npm run gen-catalog [-- --retire name]`.
 * Textures are NOT extracted here; they already live in src/assets/blocks/.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { argv, env, exit } from 'node:process';
import { format, resolveConfig } from 'prettier';
import sharp from 'sharp';
import { BASE_BLOCKS } from '../src/data/blocks.base.data.js';
import {
	assignIds, classifyAlpha, makeRows, selectCandidates, textureNames,
	type BlockstateJson, type IdMap, type Models,
} from '../src/data/catalog-rules.js';

const JAR = env.MINECRAFT_JAR ?? join(env.HOME ?? '', '.minecraft/versions/1.21.6/1.21.6.jar');
const ASSETS = 'src/assets/blocks';
const OUT_TS = 'src/data/blocks.catalog.data.ts';
const OUT_IDS = 'src/data/blocks.catalog.ids.json';

function readJsonDir<T>(dir: string): Record<string, T> {
	const out: Record<string, T> = {};
	for (const f of readdirSync(dir)) if (f.endsWith('.json')) out[f.slice(0, -5)] = JSON.parse(readFileSync(join(dir, f), 'utf8')) as T;
	return out;
}

async function alphaOfTexture(name: string): Promise<{ transparent: boolean; translucent: boolean }> {
	const img = sharp(join(ASSETS, `${name}.png`)).ensureAlpha();
	const meta = await img.metadata();
	const w = meta.width ?? 16;
	// Animated strips are taller than wide; frame 0 is what the atlas uses.
	const frame = meta.height && meta.height > w ? img.extract({ left: 0, top: 0, width: w, height: w }) : img;
	const { data } = await frame.raw().toBuffer({ resolveWithObject: true });
	const alpha: number[] = [];
	for (let i = 3; i < data.length; i += 4) alpha.push(data[i]);
	return classifyAlpha(alpha);
}

async function main() {
	if (!existsSync(JAR)) {
		console.error(`Minecraft jar not found at ${JAR}. Set MINECRAFT_JAR.`);
		exit(1);
	}
	const retire = argv.slice(2).flatMap((a, i, all) => (a === '--retire' && all[i + 1] ? [all[i + 1]] : []));

	const tmp = mkdtempSync(join(tmpdir(), 'minicraft-jar-'));
	try {
		execFileSync('unzip', ['-oq', JAR, 'assets/minecraft/models/block/*', 'assets/minecraft/blockstates/*', '-d', tmp]);
		const models = readJsonDir<Models[string]>(join(tmp, 'assets/minecraft/models/block'));
		const blockstates = readJsonDir<BlockstateJson>(join(tmp, 'assets/minecraft/blockstates'));

		const { candidates, dropped } = selectCandidates(blockstates, models, BASE_BLOCKS);
		const missingTexture = candidates.filter((c) => textureNames(c.textures).some((t) => !existsSync(join(ASSETS, `${t}.png`))));
		for (const c of missingTexture) dropped.push({ name: c.name, reason: 'texture file missing from src/assets/blocks' });
		const usable = candidates.filter((c) => !missingTexture.includes(c));

		const existing: IdMap = existsSync(OUT_IDS)
			? (JSON.parse(readFileSync(OUT_IDS, 'utf8')) as IdMap)
			: { ids: {}, retired: [] };
		const map = assignIds(existing, usable.map((c) => c.name), retire);

		const alphaCache = new Map<string, { transparent: boolean; translucent: boolean }>();
		for (const c of usable) for (const t of textureNames(c.textures)) if (!alphaCache.has(t)) alphaCache.set(t, await alphaOfTexture(t));
		const rows = makeRows(usable, map, (t) => alphaCache.get(t)!);

		const header = [
			'// GENERATED by scripts/gen-catalog.ts — do not edit by hand. Regenerate with `npm run gen-catalog`.',
			`// Source: ${JAR.replace(env.HOME ?? '', '~')}`,
			`// ${rows.filter((r) => !r.retired).length} blocks, ${rows.filter((r) => r.retired).length} retired.`,
			'// Dropped (name: reason):',
			...dropped.sort((a, b) => a.name.localeCompare(b.name)).map((d) => `//   ${d.name}: ${d.reason}`),
			"import type { BlockDef } from './blocks.base.data';",
			'',
			'export const CATALOG_BLOCKS: BlockDef[] = [',
		];
		const body = rows.map((r) => `\t${JSON.stringify(r)},`);
		// Format through the project's prettier config so the committed file is
		// stable across runs and `npm run format` never rewrites it.
		const prettierOpts = (await resolveConfig(OUT_TS)) ?? {};
		const src = await format([...header, ...body, '];', ''].join('\n'), { ...prettierOpts, filepath: OUT_TS });
		writeFileSync(OUT_TS, src);
		writeFileSync(OUT_IDS, JSON.stringify(map, null, '\t') + '\n');

		const newNames = usable.filter((c) => existing.ids[c.name] === undefined).map((c) => c.name);
		console.log(`kept ${usable.length}, dropped ${dropped.length}, new ${newNames.length}, retired ${map.retired.length}`);
		if (newNames.length) console.log(`new: ${newNames.join(' ')}`);
	} finally {
		rmSync(tmp, { recursive: true, force: true });
	}
}

main().catch((err) => {
	console.error(err);
	exit(1);
});
