/**
 * Writes server/internal/proto/catalog_gen.go: the highest block id the client knows, which the
 * server uses to reject ops (spec §5, G12). Run after any catalog change:
 * `npm run gen-server-catalog`.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { BLOCKS } from '../src/data/blocks.data.js';

// The max id, not BLOCKS.length - 1: the two agree only while BLOCKS stays dense.
const catalogMax = BLOCKS.reduce((m, b) => Math.max(m, b.id), 0);

const out = join(dirname(fileURLToPath(import.meta.url)), '../server/internal/proto/catalog_gen.go');
writeFileSync(
	out,
	`// Code generated by scripts/gen-server-catalog.ts; DO NOT EDIT.

package proto

// CatalogMax is the highest block id in src/data/blocks.data.ts BLOCKS.
const CatalogMax = ${catalogMax}
`,
);
console.log(`wrote ${out}: CatalogMax = ${catalogMax}`);
